### ISSUE TITLE
Taro 适配快手小程序共建邀请

### ISSUE THREAD

**Issue by Chen-jj** [vadxq/taro-plugin-platform-ks#1]
Hello~

我是 Taro 团队的同学，刚翻阅 [Issues](https://github.com/NervJS/taro/issues/9616) 留意到这个插件。

请问有兴趣主导快手小程序的适配吗？我们可以把此插件作为 Taro 适配快手的官方插件，在文档、物流市场等页面引导过来。另外也可以一起联系快手小程序的开发同学，共同推进对快手小程序的适配。

另外，希望在 [Taro 物料市场](https://taro-ext.jd.com/) 添加一下此插件，我们近期会收集优秀物料进行推广~

我的联系方式：798095202@qq.com

祝好！

**Comment by vadxq** [comment]
不好意思，最近有些忙碌，才回复～插件慢慢跟着更新，bug有能力解决的会帮忙解决～目前插件能力也不是很完善，api这些还没有一一比对快手和微信之间不同的api，后期需要慢慢比对一下～

**Comment by vadxq** [comment]
目前更新了一下1.3.x版本，适配tarojs v3.3.x默认不导出template

**Comment by vadxq** [comment]
https://github.com/NervJS/taro/issues/9616#issuecomment-903487838

**Comment by vadxq** [comment]
目前关联issue:
- NervJS/taro#9616
- NervJS/taro#10101
